export const CREATE_PRESET_MESSAGE = 'CREATE_PRESET_MESSAGE';
export const FETCH_PRESET_MESSAGES = 'FETCH_PRESET_MESSAGES';
export const FETCH_PRESET_MESSAGE = 'FETCH_PRESET_MESSAGE';
export const UPDATE_PRESET_MESSAGE = 'UPDATE_PRESET_MESSAGE';
export const DELETE_PRESET_MESSAGE = 'DELETE_PRESET_MESSAGE';
export const PRESET_MESSAGE_ERROR = ' PRESET_MESSAGE_ERROR';

export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
export const GROUP_MESSAGE_ERROR = 'GROUP_MESSAGE_ERROR';
export const FETCH_SENT_MESSAGES = 'FETCH_SENT_MESSAGES';
export const FETCH_SENT_MESSAGE = 'FETCH_SENT_MESSAGE';
export const SENT_MESSAGE_ERROR = 'SENT_MESSAGE_ERROR';


 