export const CREATE_SENDER = 'CREATE_SENDER';
export const FETCH_SENDERS = 'FETCH_SENDERS';
export const FETCH_SENDER = 'FETCH_SENDER';
export const UPDATE_SENDER = 'UPDATE_SENDER';
export const DELETE_SENDER = 'DELETE_SENDER';
export const SENDER_ERROR = 'SENDER_ERROR';
export const SET_SENDER_UPDATE_FORM = 'SET_SENDER_UPDATE_FORM';
export const CLEAR_SENDER_FORM = 'CLEAR_SENDER_FORM';
